BEGIN;

TRUNCATE TABLE "users" CASCADE;
TRUNCATE TABLE "oauth" CASCADE;
TRUNCATE TABLE "roles" CASCADE;
TRUNCATE TABLE "products" CASCADE;
TRUNCATE TABLE "categories" CASCADE;
TRUNCATE TABLE "products_categories" CASCADE;
TRUNCATE TABLE "images" CASCADE;
TRUNCATE TABLE "orders" CASCADE;
TRUNCATE TABLE "products_orders" CASCADE;
TRUNCATE TABLE "customers" CASCADE;
TRUNCATE TABLE "agents" CASCADE;
TRUNCATE TABLE "order_type" CASCADE;
TRUNCATE TABLE "agent_type" CASCADE;
TRUNCATE TABLE "agent_level" CASCADE;

SELECT SETVAL ((SELECT PG_GET_SERIAL_SEQUENCE('"roles"', 'id')), 1, FALSE);
SELECT SETVAL ((SELECT PG_GET_SERIAL_SEQUENCE('"categories"', 'id')), 1, FALSE);
SELECT SETVAL ((SELECT PG_GET_SERIAL_SEQUENCE('"order_type"', 'id')), 1, FALSE);
SELECT SETVAL ((SELECT PG_GET_SERIAL_SEQUENCE('"agent_type"', 'id')), 1, FALSE);
SELECT SETVAL ((SELECT PG_GET_SERIAL_SEQUENCE('"agent_level"', 'id')), 1, FALSE);

COMMIT;